[package]
name = "ocean"
version = "0.1.0"
authors = ["Vladimir Zarypov <krre31@gmail.com>"]
edition = "2018"

[lib]
name = "ocean"
path = "src/ocean/lib.rs"

[dependencies]
toml = "0.5.6"
serde = "1.0.104"
serde_derive = "1.0.104"
dirs = "2.0"
postgres = "0.17.1"
