[package]
name = "ocean"
version = "0.1.0"
authors = ["Vladimir Zarypov <krre31@gmail.com>"]
edition = "2018"

[lib]
name = "ocean"
path = "src/ocean/lib.rs"

[dependencies]
toml = "0.5.6"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
serde_derive = "1.0.104"
dirs = "2.0"
hyper = "0.13.4"
tokio = { version = "0.2", features = ["full"] }
lazy_static = "1.4.0"
diesel = { version = "1.4.4", features = ["postgres", "chrono"] }
diesel_migrations = "1.4.0"
chrono = { version = "0.4.11", features = ["serde"] }
sha1 = "0.6.0"
