[server]
port = 21000

[postgres]
host = "localhost"
port = 5432
username = "ocean"
password = ""
database = "ocean"

[telegram_bot]
interval = 600
token = ""
url = "https://api.telegram.org"
enabled = true
